### ISSUE TITLE
Business model keyphrases batch 3 - Johan van Seijen

### ISSUE THREAD

**Issue by johanvanseijen** [nexusthemes/communityrfc#16]
What goal are you trying to achieve?
Preempt competition

What’s the means to achieve it?
By having an overwhelming abundance of themes spread out over 200+ business models we can preempt a primarily feature-driven theme industry. This is the 3rd and last batch.

What’s the basis upon which you’re able to connect the means to the goal?
The last 2-3 years has seen a noticeable shift towards a content-driven theme industry, meaning the competition from other theme suppliers who also supply business themes has seen a significant increase. This shift on the supply side is in direct correlation to the increase in the demand side.

**Comment by johanvanseijen** [comment]
Ilayda is currently working on the 3d and last batch of keyphrases for us to achieve our 3-month goal of 100 themes per month. The following business models should then have search-volume related keyphrases / themes associated to them.

yoga
window cleaning
talent agency
skin care
renovation
recording studio
record label
physiotherapy
pharmacy
painter
moving
model portfolio
marketing agency
it company
interior design
graphic design
equestrian
dj
camping
butcher
animal care

**Comment by johanvanseijen** [comment]
STANS READY
yoga
skin care
renovation
moving
physiotherapy
recording studio
it company
graphic design
equestrian
dj
camping
butcher

TODO
talent agency > booking agency website template > added photos
pharmacy > added photos
record label > music label website template > added photo
painter > painting contractor website template > added photos
model portfolio > added photos to all keyphrases
interior design > home decor website template > added photos
animal care > veterinary website template > added photos
marketing agency > added photos to all keyphrases

NOT PART OF THIS BATCH
window cleaning

**Comment by nxsilayda** [comment]
All done, except:

Model portfolio > modelling > photo missing
Marketing agency > marketing wordpress theme & marketing website template > logo missing

**Comment by johanvanseijen** [comment]
STANS READY
yoga
skin care
renovation
moving
physiotherapy
recording studio
it company
graphic design
equestrian
dj
camping
butcher
actor
model portfolio
marketing agency
animal care
interior design
painter
record label
pharmacy
talent agency
