### ISSUE TITLE
Image Squeezer - Kacem Taleb

### ISSUE THREAD

**Issue by johanvanseijen** [nexusthemes/communityrfc#2]
What’s the goal you’re trying to achieve?
?

What’s the means to achieve the goal?
it would be nice to have the customer site equipped with an Image squeezer or Smusher, I'm educating my customer to be very careful on the size of the images they are uploading, i'm also recommending them to use google Photos or google drive if they do deal with tons of pictures, and it works fine so far. but still for some other customers having something that squeeze automatically the picture when they are uploaded.
plugins: EWWW Image Optimizer and WP Smush

What makes you certain your proposed means will be an effective one?

**Comment by barkgj** [comment]
The plugin can be installed and activated manually for every partner, in case you like to have this functionality available for your clients. Note; its still a manual process to enable/activate the plugin.
