### ISSUE TITLE
Reseller "getting started" video - Johan van Seijen

### ISSUE THREAD

**Issue by johanvanseijen** [nexusthemes/communityrfc#31]
What goal are you trying to achieve?
Boost operations

What's the means to achieve it?
A significant percentage of people first starting the studio ask the question of how to get started. If would help if a link to one or more studio videos are in the reseller welcome mail.

What’s the basis upon which you’re able to connect the means to the goal?
I currently get support mails with this question. Making people more self-reliant and pro actively answering this very obvious question is the way to go to remove these unwanted support question and stop squandering resources (me working on Sunday answering these kind of mails).

**Comment by barkgj** [comment]
Finished it; https://www.youtube.com/watch?v=0xEPBaTjldI
This video is now also send in the welcome mail when the studio is created (once a reseller signs up).
