### ISSUE TITLE
Add more business types to portfolio

### ISSUE THREAD

**Issue by barkgj** [nexusthemes/communityrfc#33]
What’s the means to achieve it?
Make themes for the following business types: 
Genealogy, home party type themes (such as candles, jewelry, Tupperware)

What’s the basis upon which you’re able to connect the means to the goal? (facts and numbers)
Not specified

**Comment by barkgj** [comment]
I suggest to better manage these requests, we should allow resellers (and other people visiting the website) to fill in a form that allows people to submit the basic information about the business type (like what services are to be part of this). This could optionally result in a new theme to be included in the portfolio or perhaps in a custom theme. That way the community can help us extend the business types by submitting info. As a MVP the image selection process should be still done by us, although also that part could be integrated with 123rf API's probably.

**Comment by johanvanseijen** [comment]
Closed this issue. Enabling other themes providers is a suggested solution to this issue: https://github.com/nexusthemes/wordpress-themes-portfolio/issues/22
